# Form implementation generated from reading ui file 'C:\Users\Jared\Documents\Code\Python-Projects\Inventory Manager\ui\widgets\structural_steel_tab.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1057, 667)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 6, 9, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_17.addLayout(self.verticalLayout_10)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setContentsMargins(9, 3, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_popout = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_popout.sizePolicy().hasHeightForWidth())
        self.pushButton_popout.setSizePolicy(sizePolicy)
        self.pushButton_popout.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_popout.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_popout.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_popout.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Jared\\Documents\\Code\\Python-Projects\\Inventory Manager\\ui\\widgets\\../../icons/open_in_new.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_popout.setIcon(icon)
        self.pushButton_popout.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_popout.setFlat(True)
        self.pushButton_popout.setObjectName("pushButton_popout")
        self.horizontalLayout_2.addWidget(self.pushButton_popout)
        self.verticalLayout_23.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_23.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_add_new_structural_item = QtWidgets.QPushButton(parent=Form)
        self.pushButton_add_new_structural_item.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_add_new_structural_item.sizePolicy().hasHeightForWidth())
        self.pushButton_add_new_structural_item.setSizePolicy(sizePolicy)
        self.pushButton_add_new_structural_item.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_add_new_structural_item.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton_add_new_structural_item.setFont(font)
        self.pushButton_add_new_structural_item.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.pushButton_add_new_structural_item.setToolTip("")
        self.pushButton_add_new_structural_item.setStyleSheet("")
        self.pushButton_add_new_structural_item.setCheckable(False)
        self.pushButton_add_new_structural_item.setDefault(True)
        self.pushButton_add_new_structural_item.setObjectName("pushButton_add_new_structural_item")
        self.verticalLayout_2.addWidget(self.pushButton_add_new_structural_item)
        self.verticalLayout_23.addLayout(self.verticalLayout_2)
        self.horizontalLayout_17.addLayout(self.verticalLayout_23)
        self.horizontalLayout_17.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_17)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_add_new_structural_item.setStatusTip(_translate("Form", "Create a new item"))
        self.pushButton_add_new_structural_item.setText(_translate("Form", "Add New Structural Item to Inventory"))
