# Form implementation generated from reading ui file '/mnt/60F41785F4175C9A/Forge/Inventory Manager/ui/widgets/structural_steel_settings_tab.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1010, 587)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 9, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.tabWidget = QtWidgets.QTabWidget(parent=Form)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.price_per_pound_tab = QtWidgets.QWidget()
        self.price_per_pound_tab.setObjectName("price_per_pound_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.price_per_pound_tab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.price_per_pound_layout = QtWidgets.QVBoxLayout()
        self.price_per_pound_layout.setObjectName("price_per_pound_layout")
        self.verticalLayout.addLayout(self.price_per_pound_layout)
        self.tabWidget.addTab(self.price_per_pound_tab, "")
        self.pounds_per_cubic_foot_tab = QtWidgets.QWidget()
        self.pounds_per_cubic_foot_tab.setObjectName("pounds_per_cubic_foot_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pounds_per_cubic_foot_tab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pounds_per_cubic_foot_layout = QtWidgets.QVBoxLayout()
        self.pounds_per_cubic_foot_layout.setContentsMargins(-1, 6, -1, -1)
        self.pounds_per_cubic_foot_layout.setObjectName("pounds_per_cubic_foot_layout")
        self.verticalLayout_4.addLayout(self.pounds_per_cubic_foot_layout)
        self.tabWidget.addTab(self.pounds_per_cubic_foot_tab, "")
        self.verticalLayout_15.addWidget(self.tabWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_15)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(9, 9, 0, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_5.addItem(spacerItem)
        self.pushButton_popout = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_popout.sizePolicy().hasHeightForWidth())
        self.pushButton_popout.setSizePolicy(sizePolicy)
        self.pushButton_popout.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_popout.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_popout.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_popout.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("/mnt/60F41785F4175C9A/Forge/Inventory Manager/ui/widgets/../../icons/open_in_new.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButton_popout.setIcon(icon)
        self.pushButton_popout.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_popout.setFlat(True)
        self.pushButton_popout.setObjectName("pushButton_popout")
        self.horizontalLayout_5.addWidget(self.pushButton_popout)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.materials_list = QtWidgets.QListWidget(parent=self.groupBox_2)
        self.materials_list.setObjectName("materials_list")
        self.verticalLayout_6.addWidget(self.materials_list)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_add_material = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_add_material.setDefault(False)
        self.pushButton_add_material.setFlat(True)
        self.pushButton_add_material.setObjectName("pushButton_add_material")
        self.horizontalLayout_2.addWidget(self.pushButton_add_material)
        self.pushButton_remove_material = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_remove_material.setDefault(False)
        self.pushButton_remove_material.setFlat(True)
        self.pushButton_remove_material.setObjectName("pushButton_remove_material")
        self.horizontalLayout_2.addWidget(self.pushButton_remove_material)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.verticalLayout_5.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.materials_list, self.pushButton_add_material)
        Form.setTabOrder(self.pushButton_add_material, self.pushButton_remove_material)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.price_per_pound_tab),
            _translate("Form", "Price Per Pound"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.pounds_per_cubic_foot_tab),
            _translate("Form", "Pounds Per Cubic Foot"),
        )
        self.groupBox_2.setTitle(_translate("Form", "Materials"))
        self.pushButton_add_material.setText(_translate("Form", "Add"))
        self.pushButton_remove_material.setText(_translate("Form", "Remove"))
