# Form implementation generated from reading ui file '/mnt/60F41785F4175C9A/Forge/Inventory Manager/ui/dialogs/items_change_quantity_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(484, 406)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 462, 219))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblMessage = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMessage.sizePolicy().hasHeightForWidth())
        self.lblMessage.setSizePolicy(sizePolicy)
        self.lblMessage.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.lblMessage.setWordWrap(True)
        self.lblMessage.setObjectName("lblMessage")
        self.verticalLayout_4.addWidget(self.lblMessage)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.addWidget(self.scrollArea)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.groupBox = QtWidgets.QGroupBox(parent=self.widget)
        self.groupBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_item = QtWidgets.QPushButton(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_item.sizePolicy().hasHeightForWidth())
        self.pushButton_item.setSizePolicy(sizePolicy)
        self.pushButton_item.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_item.setStyleSheet("")
        self.pushButton_item.setCheckable(True)
        self.pushButton_item.setAutoDefault(False)
        self.pushButton_item.setFlat(True)
        self.pushButton_item.setObjectName("pushButton_item")
        self.gridLayout.addWidget(self.pushButton_item, 0, 1, 1, 1)
        self.pushButton_category = QtWidgets.QPushButton(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_category.sizePolicy().hasHeightForWidth())
        self.pushButton_category.setSizePolicy(sizePolicy)
        self.pushButton_category.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_category.setStyleSheet("")
        self.pushButton_category.setCheckable(True)
        self.pushButton_category.setChecked(False)
        self.pushButton_category.setAutoDefault(False)
        self.pushButton_category.setFlat(True)
        self.pushButton_category.setObjectName("pushButton_category")
        self.gridLayout.addWidget(self.pushButton_category, 0, 0, 1, 1)
        self.label_component_selected = QtWidgets.QLabel(parent=self.groupBox)
        self.label_component_selected.setText("")
        self.label_component_selected.setObjectName("label_component_selected")
        self.gridLayout.addWidget(self.label_component_selected, 1, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.doubleSpinBox_quantity = QtWidgets.QDoubleSpinBox(parent=self.widget)
        self.doubleSpinBox_quantity.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBox_quantity.setMaximum(99999999.0)
        self.doubleSpinBox_quantity.setObjectName("doubleSpinBox_quantity")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_quantity)
        spacerItem1 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        spacerItem2 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.buttonsLayout.addItem(spacerItem2)
        self.pushButton_add = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_add.setEnabled(False)
        self.pushButton_add.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_add.setObjectName("pushButton_add")
        self.buttonsLayout.addWidget(self.pushButton_add)
        self.pushButton_remove = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_remove.setEnabled(False)
        self.pushButton_remove.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.buttonsLayout.addWidget(self.pushButton_remove)
        self.pushButton_cancel = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_cancel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.buttonsLayout.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.buttonsLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.widget)
        self.label.setBuddy(self.doubleSpinBox_quantity)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.pushButton_category, self.pushButton_item)
        Form.setTabOrder(self.pushButton_item, self.doubleSpinBox_quantity)
        Form.setTabOrder(self.doubleSpinBox_quantity, self.pushButton_add)
        Form.setTabOrder(self.pushButton_add, self.pushButton_remove)
        Form.setTabOrder(self.pushButton_remove, self.pushButton_cancel)
        Form.setTabOrder(self.pushButton_cancel, self.scrollArea)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lblMessage.setText(_translate("Form", "TextLabel"))
        self.groupBox.setTitle(_translate("Form", "Change Quantities by"))
        self.pushButton_item.setToolTip(_translate("Form", "Will remove quantities from the selected components."))
        self.pushButton_item.setText(_translate("Form", "Selected Item"))
        self.pushButton_category.setToolTip(
            _translate(
                "Form",
                "Will remove quantities from all items in the category that is currently open.",
            )
        )
        self.pushButton_category.setText(_translate("Form", "All Items in Category"))
        self.label.setText(_translate("Form", "Quantity:"))
        self.doubleSpinBox_quantity.setToolTip(_translate("Form", "Quantity multiplier/amount you want to remove by."))
        self.pushButton_add.setText(_translate("Form", "Add Quantity"))
        self.pushButton_remove.setText(_translate("Form", "Remove Quantity"))
        self.pushButton_cancel.setText(_translate("Form", "Cancel"))
