# Form implementation generated from reading ui file 'C:\Users\Jared\Documents\Code\Python-Projects\Inventory Manager\ui\dialogs\view_removed_quantities_history_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1933, 883)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.categoryHistoryTable = QtWidgets.QTableWidget(parent=self.groupBox_2)
        self.categoryHistoryTable.setEnabled(True)
        self.categoryHistoryTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.categoryHistoryTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.categoryHistoryTable.setRowCount(0)
        self.categoryHistoryTable.setColumnCount(2)
        self.categoryHistoryTable.setObjectName("categoryHistoryTable")
        self.categoryHistoryTable.horizontalHeader().setDefaultSectionSize(500)
        self.categoryHistoryTable.horizontalHeader().setMinimumSectionSize(42)
        self.categoryHistoryTable.verticalHeader().setDefaultSectionSize(30)
        self.categoryHistoryTable.verticalHeader().setMinimumSectionSize(28)
        self.horizontalLayout_12.addWidget(self.categoryHistoryTable)
        self.horizontalLayout_11.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.singleItemHistoryTable = QtWidgets.QTableWidget(parent=self.groupBox_3)
        self.singleItemHistoryTable.setEnabled(True)
        self.singleItemHistoryTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.singleItemHistoryTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.singleItemHistoryTable.setRowCount(0)
        self.singleItemHistoryTable.setColumnCount(2)
        self.singleItemHistoryTable.setObjectName("singleItemHistoryTable")
        self.singleItemHistoryTable.horizontalHeader().setDefaultSectionSize(500)
        self.singleItemHistoryTable.horizontalHeader().setMinimumSectionSize(42)
        self.horizontalLayout_13.addWidget(self.singleItemHistoryTable)
        self.horizontalLayout_11.addWidget(self.groupBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_2.setTitle(_translate("Form", "Category History"))
        self.groupBox_3.setTitle(_translate("Form", "Single Item History"))
