class DialogButtons:
    """A class that contains constants."""

    ok: str = "Ok"
    ok_cancel: str = "Ok, Cancel"
    cancel: str = "Cancel"
    no: str = "No"
    copy: str = "Copy"
    save: str = "Save"
    add: str = "Add"
    delete: str = "Delete"
    clone: str = "Clone"
    update: str = "Update"
    delete_cancel: str = "Delete, Cancel"
    clone_cancel: str = "Clone, Cancel"
    add_cancel: str = "Add, Cancel"
    yes_no_cancel: str = "Yes, No, Cancel"
    save_cancel: str = "Save, Cancel"
    open_cancel: str = "Open, Cancel"
    ok_update: str = "Ok, Update"
    ok_copy_cancel: str = "Ok, Copy, Cancel"
    ok_save_copy_cancel: str = "Ok, Save, Copy, Cancel"
