# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Code\Python-Projects\Inventory Manager\ui\add_item_dialog_price_of_steel.ui'
#
# Created by: PyQt6 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(542, 275)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet(
            "QWidget#widget{\n"
            "    border-top-left-radius:10px;\n"
            "    border-bottom-left-radius:10px;\n"
            "    border-top-right-radius:10px;\n"
            "    border-bottom-right-radius:10px;\n"
            "    border: 1px solid  rgb(0,120,212);;\n"
            "}"
        )
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblTitle = QtWidgets.QLabel(self.widget)
        self.lblTitle.setMinimumSize(QtCore.QSize(0, 30))
        self.lblTitle.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblTitle.setFont(font)
        self.lblTitle.setStyleSheet(
            "background-color: rgb(0,120,212);\n"
            "border-top-left-radius:10px;\n"
            "border-top-right-radius:10px;\n"
            "border: 1px solid  rgb(0,120,212);\n"
            ""
        )
        self.lblTitle.setFrameShape(QtWidgets.QFrame.Box)
        self.lblTitle.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblTitle.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout_3.addWidget(self.lblTitle)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.iconHolder = QtWidgets.QVBoxLayout()
        self.iconHolder.setSpacing(0)
        self.iconHolder.setObjectName("iconHolder")
        self.verticalLayout_2.addLayout(self.iconHolder)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 492, 79))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblMessage = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMessage.sizePolicy().hasHeightForWidth())
        self.lblMessage.setSizePolicy(sizePolicy)
        self.lblMessage.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.lblMessage.setObjectName("lblMessage")
        self.verticalLayout_4.addWidget(self.lblMessage)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.addWidget(self.scrollArea)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.comboBox_group = QtWidgets.QComboBox(self.widget)
        self.comboBox_group.setEditable(True)
        self.comboBox_group.setCurrentText("")
        self.comboBox_group.setObjectName("comboBox_group")
        self.gridLayout.addWidget(self.comboBox_group, 4, 1, 1, 1)
        self.spinBox_current_quantity = QtWidgets.QSpinBox(self.widget)
        self.spinBox_current_quantity.setAccelerated(True)
        self.spinBox_current_quantity.setMaximum(9999999)
        self.spinBox_current_quantity.setObjectName("spinBox_current_quantity")
        self.gridLayout.addWidget(self.spinBox_current_quantity, 3, 1, 1, 1)
        self.comboBox_thickness = QtWidgets.QComboBox(self.widget)
        self.comboBox_thickness.setEditable(False)
        self.comboBox_thickness.setObjectName("comboBox_thickness")
        self.gridLayout.addWidget(self.comboBox_thickness, 2, 1, 1, 1)
        self.lineEdit_material = QtWidgets.QComboBox(self.widget)
        self.lineEdit_material.setEditable(False)
        self.lineEdit_material.setObjectName("lineEdit_material")
        self.gridLayout.addWidget(self.lineEdit_material, 1, 1, 1, 1)
        self.lineEdit_sheet_dim = QtWidgets.QComboBox(self.widget)
        self.lineEdit_sheet_dim.setEditable(False)
        self.lineEdit_sheet_dim.setObjectName("lineEdit_sheet_dim")
        self.gridLayout.addWidget(self.lineEdit_sheet_dim, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 3)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.verticalLayout.addLayout(self.buttonsLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit_sheet_dim, self.lineEdit_material)
        Form.setTabOrder(self.lineEdit_material, self.comboBox_thickness)
        Form.setTabOrder(self.comboBox_thickness, self.spinBox_current_quantity)
        Form.setTabOrder(self.spinBox_current_quantity, self.comboBox_group)
        Form.setTabOrder(self.comboBox_group, self.scrollArea)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lblTitle.setText(_translate("Form", "TextLabel"))
        self.lblMessage.setText(_translate("Form", "TextLabel"))
        self.label_10.setText(_translate("Form", "Thickness:"))
        self.label_6.setText(_translate("Form", "Material:"))
        self.label_7.setText(_translate("Form", "Current Quantity:"))
        self.label.setText(_translate("Form", "Sheet Dimension:"))
        self.label_8.setText(_translate("Form", "Group:"))
